apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: single-nodejs-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: single-nodejs-app
    app.kubernetes.io/part-of: single-nodejs-app
  name: single-nodejs-app
  namespace: jduimovich
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: single-nodejs-app
status:
  loadBalancer: {}
